cleanup(OWNERS): remove inactive approvers
falcosecurity/client-go pull request #57
Opened 2022-07-05 15:12 UTC by jasondellaluce

**What type of PR is this?**

/kind cleanup

/kind documentation

**Any specific area of the project related to this PR?**

/area examples

**What this PR does / why we need it**:

For https://github.com/falcosecurity/falco/issues/2115, this PR moves inactive approvers (who had very little or zero contributions over the past 6 months) from `approvers` to `emeritus_approvers` in OWNERS.

Considering the low activity of this repository, devstats have also been consulted for the past year: https://falco.devstats.cncf.io/d/9/developer-activity-counts-by-repository-group-table?orgId=1&var-period_name=Last%20year&var-metric=contributions&var-repogroup_name=falcosecurity%2Fclient-go&var-country_name=All

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2022-07-05 15:12 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/client-go/pull/57#" title="Author self-approved">jasondellaluce</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **markyjackson-taulia** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @markyjackson-taulia` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Fclient-go).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/client-go/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["markyjackson-taulia"]} -->

2022-07-06 10:34 UTC, fntlnz requested changes
Please restore `fntlnz` https://github.com/falcosecurity/falco/issues/2115#issuecomment-1176045086

2022-07-13 14:07 UTC, leogr commented
Hey @fntlnz If you decided to step down, could you remove the _change request_ to unblock this PR?

@falcosecurity/client-go-maintainers any other thoughts on this?

2022-07-18 14:21 UTC, jasondellaluce commented
@fntlnz confirmed his intention to step down as an approver in #58, however neither this PR nor #58 can be merged due to a change request and a missing sign-off respectively, and there has been no response to https://github.com/falcosecurity/client-go/pull/57#issuecomment-1183273388 either.

Closing this in favor of #59 to unblock this changes.

/close

2022-07-18 14:21 UTC, closed without merging

2022-07-18 14:21 UTC, poiana commented
@jasondellaluce: Closed this PR.

<details>

In response to [this](https://github.com/falcosecurity/client-go/pull/57#issuecomment-1187559052):

>@fntlnz confirmed his intention to step down as an approver in #58, however neither this PR nor #58 can be merged due to a change request and a missing sign-off respectively, and there has been no response to https://github.com/falcosecurity/client-go/pull/57#issuecomment-1183273388 either.
>
>Closing this in favor of #59 to unblock this changes.
>
>/close


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>